import type { EmailContent, InquiryEmailInput } from "@/lib/email/types";
import { emailShell, escapeHtml, row } from "@/lib/email/templates/shared";

export function inquiryNotificationTemplate(input: InquiryEmailInput): EmailContent {
  const context = input.company || input.country;
  const subject = `New Auctus Heritage Inquiry - ${input.name} - ${context}`;
  const productRows = input.items.length ? input.items.map((item) => `<tr><td style="padding:12px 0;border-top:1px solid #eee"><a href="${escapeHtml(item.productUrl)}" style="font-weight:700;color:#2c6f6d">${escapeHtml(item.name)}</a><br><span style="font-size:13px;color:#666">Quantity: ${item.quantity}${item.notes ? ` · ${escapeHtml(item.notes)}` : ""}</span></td></tr>`).join("") : `<tr><td style="padding:12px 0;color:#666">No products selected.</td></tr>`;
  const detailRows = [row("Inquiry ID", input.id), row("Submitted", new Date(input.createdAt).toLocaleString("en-US", { timeZone: "America/New_York" })), row("Name", input.name), row("Email", input.email), row("Company / Organization", input.company), row("Position / Role", input.position), row("Country", input.country), row("Phone", input.phone), row("Estimated quantity", input.estimatedQuantity), row("Preferred language", input.preferredLanguage), row("Source", input.source), row("Source page", input.sourcePage), row("Referrer", input.referrer)].join("");
  const html = emailShell(subject, `<h1 style="margin:28px 0 8px;font-size:24px">New inquiry received</h1><p style="margin:0 0 20px;color:#666;line-height:1.6">The inquiry has been saved in the admin system.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0">${detailRows}</table><h2 style="margin:26px 0 8px;font-size:17px">Selected products</h2><table role="presentation" width="100%" cellspacing="0" cellpadding="0">${productRows}</table><h2 style="margin:26px 0 8px;font-size:17px">Message</h2><div style="white-space:pre-wrap;background:#f7f5f0;padding:16px;font-size:14px;line-height:1.7">${escapeHtml(input.message || "No message provided.")}</div><a href="https://auctusheritage.com/admin/inquiries/${encodeURIComponent(input.id)}" style="display:inline-block;margin-top:24px;background:#171717;color:#fff;text-decoration:none;padding:13px 18px;font-weight:700">Open inquiry in admin</a>`);
  const products = input.items.length ? input.items.map((item) => `- ${item.name} | Quantity: ${item.quantity} | ${item.productUrl}${item.notes ? ` | ${item.notes}` : ""}`).join("\n") : "No products selected.";
  const text = `New Auctus Heritage inquiry\n\nInquiry ID: ${input.id}\nSubmitted: ${input.createdAt}\nName: ${input.name}\nEmail: ${input.email}\nCompany / Organization: ${input.company || "Not provided"}\nPosition / Role: ${input.position || "Not provided"}\nCountry: ${input.country}\nPhone: ${input.phone || "Not provided"}\nEstimated quantity: ${input.estimatedQuantity || "Not provided"}\nPreferred language: ${input.preferredLanguage}\nSource: ${input.source}\nSource page: ${input.sourcePage || "Not provided"}\nReferrer: ${input.referrer || "Not provided"}\n\nSelected products:\n${products}\n\nMessage:\n${input.message || "No message provided."}\n\nAdmin: https://auctusheritage.com/admin/inquiries/${input.id}`;
  return { subject, html, text };
}
