import type { Locale } from "@/lib/i18n";

export function AboutCompany({ locale }: { locale: Locale }) {
  const isZh = locale === "zh";
  return <section className="bg-[#fffdf8]"><div className="mx-auto grid max-w-6xl gap-10 px-4 py-12 sm:px-5 sm:py-16 lg:grid-cols-[220px_1fr] lg:gap-16 lg:py-20"><aside><p className="section-kicker">{isZh ? "我们的故事" : "Our Story"}</p><div className="mt-6 h-2 w-24 bg-[#f9d95f]" /><div className="mt-2 h-2 w-16 bg-[#65c6c4]" /><div className="mt-2 h-2 w-10 bg-[#f27a5e]" /></aside><div className="max-w-3xl space-y-5 text-[15px] leading-7 text-[#464646] sm:text-base sm:leading-8"><p>{isZh ? "Little Treasures From China 是由 Auctus Lab LLC 运营的文化产品品牌。Auctus Lab LLC 是一家在美国纽约州注册的公司。" : "Little Treasures From China is a cultural product brand operated by Auctus Lab LLC, a company registered in New York, USA."}</p><p>{isZh ? "我们开发并甄选来自中国的博物馆灵感产品、教育用品、家居好物、文具、收藏品与文化礼品。每件产品都以设计、来源与日常使用价值为出发点。" : "We develop and curate museum-inspired, educational, home, stationery, collectible, and cultural products from China. Each object is considered for its design, provenance, and place in everyday life."}</p><p>{isZh ? "我们希望以清晰、尊重且当代的方式，让中国文化故事进入全球消费者、教育者、收藏者与文化机构的日常生活。" : "Our work introduces Chinese cultural stories to global customers, educators, collectors, and institutions through objects that feel considered, useful, and contemporary."}</p></div></div><div className="border-y border-black/10 bg-white"><div className="mx-auto grid max-w-6xl gap-8 px-4 py-12 sm:px-5 sm:py-16 md:grid-cols-2 md:gap-14"><article><p className="section-kicker">{isZh ? "关于 Auctus Lab" : "About Auctus Lab"}</p><h2 className="mt-4 text-2xl font-black sm:text-3xl">Auctus Lab LLC</h2><p className="mt-4 max-w-xl text-[15px] leading-7 text-[#555]">{isZh ? "Auctus Lab 是一家位于纽约的产品创新与全球电子商务公司，专注于连接文化内容、优质设计与国际市场。" : "Auctus Lab is a New York-based product innovation and global e-commerce company connecting cultural content, thoughtful design, and international markets."}</p></article><article><p className="section-kicker">{isZh ? "公司信息" : "Company Information"}</p><dl className="mt-4 divide-y divide-black/10 border-y border-black/10 text-sm"><CompanyRow label={isZh ? "公司" : "Company"} value="Auctus Lab LLC" /><CompanyRow label={isZh ? "所在地" : "Location"} value="New York, USA" /><CompanyRow label={isZh ? "业务" : "Focus"} value="Product Innovation & Global E-commerce" /></dl></article></div></div><div className="mx-auto flex max-w-6xl justify-center px-4 py-10 sm:px-5"><span className="inline-flex border border-black/20 px-4 py-2 text-[11px] font-black uppercase tracking-[0.14em] text-[#555]">A Brand by Auctus Lab LLC · New York, USA</span></div></section>;
}

function CompanyRow({ label, value }: { label: string; value: string }) {
  return <div className="grid grid-cols-[100px_1fr] gap-4 py-4"><dt className="text-[#777]">{label}</dt><dd className="font-bold">{value}</dd></div>;
}
